TrajectoryPlannerROS:
  meter_scoring: true
  max_vel_x: 0.50
  min_vel_x: 0.10
  max_vel_theta: 0.86
  min_vel_theta: -0.86
  min_in_place_vel_theta: 0.4
  acc_lim_theta: 2.5
  acc_lim_x: 0.50
  acc_lim_y: 0.0

  holonomic_robot: false
  yaw_goal_tolerance: 0.3
  xy_goal_tolerance: 0.15
  sim_time: 1.0
  gdist_scale: 0.6
  pdist_scale: 3.2
  occdist_scale: 0.01
  # sim_granularity: 0.025
  # angular_sim_granularity: 0.025
  # heading_lookahead: 0.325
  oscillation_reset_dist: 0.05
  escape_reset_dist: 0.1
  escape_reset_theta: 1.57079632679
  escape_vel: -0.1
  vx_samples: 8
  vtheta_samples: 20
  dwa: true

  # heading_lookahead: 0.325
  # heading_scoring: false
  # heading_scoring_timestep: 0.8
  # simple_attractor: false
