transform_tolerance: 0.2
obstacle_range: 2.5
raytrace_range: 3.0
footprint: [[0.235,0.185],[-0.235,0.185],[-0.235,-0.185],[0.235,-0.185]]
inflation_radius: 0.40

observation_sources: scan scan_filtered

scan: {data_type: LaserScan, topic: scan, expected_update_rate: 0.2, marking: false, clearing: true}

scan_filtered: {data_type: LaserScan, topic: scan_filtered, expected_update_rate: 0.15, marking: true, clearing: false}